@extends('layouts.app')

@section('content')
<main>
    <section class="section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col" style="max-width: 960px">
                    <h1 class="text-center display-4 mb-4">特定商取引法表示</h1>
                    <div class="card shadow border-gray-300 p-4 p-lg-5">
                        <table class="table table-two-colums">
                            <tbody>
                                <tr>
                                    <th>販売業者
                                    </th>
                                    <td>COLORBOX株式会社</td>
                                </tr>
                                <tr>
                                    <th>代表責任者
                                    </th>
                                    <td>高井昭彦</td>
                                </tr>
                                <tr>
                                    <th>所在地
                                    </th>
                                    <td>
                                        〒１５０-０００１<br>
                                        東京都渋谷区神宮前六丁目２３番４号
                                    </td>
                                </tr>
                                <tr>
                                    <th>電話番号
                                    </th>
                                    <td>090-6124-7916</td>
                                </tr>
                                <tr>
                                    <th>電話受付時間
                                    </th>
                                    <td>8:00 - 17:00</td>
                                </tr>
                                <tr>
                                    <th>メールアドレス
                                    </th>
                                    <td>info@colorbox.tech</td>
                                </tr>
                                <tr>
                                    <th>サイトURL
                                    </th>
                                    <td>https://colorbox.tech</td>
                                </tr>
                                <tr>
                                    <th>販売価格
                                    </th>
                                    <td>各商品の紹介ページに記載している価格とします。</td>
                                </tr>
                                <tr>
                                    <th>商品代金以外に必要な料金
                                    </th>
                                    <td>
                                        消費税、送料（全国一律３８０円）<br>
                                        ※２，０００円以上購入すれば送料無料、ラッピング代１００円（希望者のみ）
                                    </td>
                                </tr>
                                <tr>
                                    <th>引き渡し時期
                                    </th>
                                    <td>ご注文から３日以内に発送します。</td>
                                </tr>
                                <tr>
                                    <th>お支払い方法とお支払いの時期
                                    </th>
                                    <td>
                                        クレジットカード決済：ご注文時にお支払いが確定します。<br>
                                        代金引換：代金は商品お届け時、配送員に現金でお支払いください。<br>
                                        コンビニ決済：ご注文から３日以内に、コンビニでお支払いください。
                                    </td>
                                </tr>
                                <tr>
                                    <th>返品・交換・キャンセルについて
                                    </th>
                                    <td>
                                        商品発送後の返品・交換・キャンセルには、基本的に対応しておりません。<br>
                                        商品に欠陥がある場合のみ交換が可能ですのでご連絡ください。
                                    </td>
                                </tr>
                                <tr>
                                    <th>返品期限
                                    </th>
                                    <td>商品出荷から１０日以内にご連絡ください。</td>
                                </tr>
                                <tr>
                                    <th>返品送料
                                    </th>
                                    <td>
                                        商品に欠陥がある場合は、弊社で負担いたします。<br>
                                        それ以外は、お客さまのご負担になります。
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>
@endsection
